### ISSUE TITLE
example of calling a service (plugin) from client (c++)

### ISSUE THREAD

**Issue by bioothod** [cocaine/cocaine-framework-native#16]
Please take a look at https://groups.google.com/forum/#!topic/reverbrain/jgxKjxIk-wY
and answer into the maillist

can you explain me please how to properly write own realisation of a cocaine::framework::service_t like that? https://github.com/cocaine/cocaine-framework-native/blob/v0.11/include/cocaine/framework/services/storage.hpp

my goal is writing yet another service for cocaine_runtime and now  the question arises how to calling my service from client side. what is a best way in v11?

Продублирую на великом и могучем вопрос, а то англицкий корявый. :)
Есть собственный сервис(плагин), который устанавливается и отлично работает в cocaine_runtime. Теперь хочется подёргать его из плюсового клиента, но непонятно как это сделать лучше в реалиях v11. Пытаюсь осознать можно ли сделать в таком виде: https://github.com/cocaine/cocaine-framework-native/blob/v0.11/include/cocaine/framework/services/storage.hpp
,но непонятно что делать в месте вызова call, ведь надо как-то указать что именно дёргать(какой метод, какой сервис):

**Comment by Kobolog** [comment]
Essentially, you invoke `call` method template of the `service_t` base by providing a _message_ type and message _arguments_:

```
call<cocaine::io::storage::read>(collection, key);
```

Message types are defined in the service definition file (IDL, kind of), that file with all those tuple_type, upstream_type and other typedefs.

**Comment by Kobolog** [comment]
I'm going to forward this to the group.

**Comment by bioothod** [comment]
Thank you
