### ISSUE TITLE
example of using worker

### ISSUE THREAD

**Issue by sabotennn** [cocaine/cocaine-framework-native#25]
Here the sample https://github.com/cocaine/cocaine-framework-native/blob/master/example/echo/main.cpp
I have a postgresql connection (libpq) created in lamda expression, so i can use it without problem, but when i try to create connetion out of lambda and pass it through lambda won't start at all.
So, will this lamda expression called in the same thread in which created? May it be the problem?

**Comment by 3Hren** [comment]
All handlers are called using a separate thread pool, where thread's number currently can't be configured (I just forgot to), but by default it's equal to `hardware_concurrency`.

The main thread is responsible for all I/O operations between Cocaine and the worker, and it shouldn't be blocked ever.

**Comment by sabotennn** [comment]
Thank you.
